Repository TeamTuesday/siso-backend, pull requests merged in 2022-06, with the labels that each got.

#5 Feat: [SISO-16] git message template 추가
  .gitmessage
Labels: size/S

#6 Chore: [SISO-37] PR 템플릿 적용
  .github/pull_request_template.md
Labels: size/S

#7 Chore: [SISO-42] 환경변수 관련 세팅
  .env
  .gitignore
  README.md
  libs/config/src/config.module.ts
  libs/config/src/config.service.spec.ts
  libs/config/src/config.service.ts
  libs/config/src/index.ts
  libs/config/tsconfig.lib.json
  nest-cli.json
  package.json
  src/app.module.ts
  src/main.ts
  test/jest-e2e.json
  tsconfig.json
  yarn.lock
Labels: size/L

#9 Feat: [SISO-55] 샘플(Notes) 컨트롤러 및 서비스 레이어 추가
  package.json
  src/app.module.ts
  src/notes/fixtures/notes.ts
  src/notes/interfaces/notes.d.ts
  src/notes/notes.controller.spec.ts
  src/notes/notes.controller.ts
  src/notes/notes.module.ts
  src/notes/notes.service.spec.ts
  src/notes/notes.service.ts
  src/types/utils.d.ts
  yarn.lock
Labels: size/L

#8 Fix: [NO-ISSUE] Config 모듈 전역으로 사용 가능하도록 수정
  libs/config/src/config.module.ts
Labels: size/XS

#12 fix: [NO-ISSUE] CODEOWNERS 내 멤버 참조를 팀으로 지정
  .github/CODEOWNERS
Labels: size/XS

#11 Feat: [SISO-33] [SISO-34] typeorm 세팅 및 db 마이그레이션
  .env
  libs/config/src/config.module.ts
  libs/config/src/config.service.ts
  libs/config/src/database/database.module.ts
  libs/config/src/database/database.service.spec.ts
  libs/config/src/database/database.service.ts
  package.json
  src/app.module.ts
  src/migration/1655265681090-Test.ts
  src/vote-subject/entity/vote-subject.entity.ts
  src/vote-subject/vote-subject.module.ts
  yarn.lock
Labels: size/L
