Repository TeamTuesday/siso-backend, pull requests merged in 2022-07, with the labels that each got.

#13 Feat: [SISO-73] 투표 더미 리소스 조회 API 추가
  src/app.module.ts
  src/vote-subjects/vote-subjects.controller.spec.ts
  src/vote-subjects/vote-subjects.controller.ts
  src/vote-subjects/vote-subjects.module.ts
  src/vote-subjects/vote-subjects.service.spec.ts
  src/vote-subjects/vote-subjects.service.ts
Labels: size/L, hold

#15 Fix: [NO-ISSUE] yarn.lock 변경 반영
  yarn.lock
Labels: size/XS

#16 [SISO-88] Docs: README.md 데이터 베이스 환경 구성 추가
  README.md
  libs/config/src/database/database.service.ts
Labels: size/XS

#17 Feat: [SISO-89] cors 허용
  src/main.ts
Labels: size/XS

#20 Feat: [SISO-85] 투표 정보 API에 문서화 적용
  src/vote-subjects/vote-subjects.controller.ts
Labels: size/S

#19 Refactor: [SISO-86] vote-subject entity 레이어 병합
  libs/config/src/database/database.service.ts
  src/app.module.ts
  src/vote-subject/vote-subject.module.ts
  src/vote-subjects/entities/vote-subject.entity.ts
  src/vote-subjects/vote-subjects.module.ts
Labels: size/S

#18 Fix: [SISO-34] typeorm migration
  README.md
  libs/config/src/database/database.module.ts
  libs/config/src/database/database.service.ts
  package.json
  src/ormconfig.ts
  tsconfig.json
Labels: size/M
