Repository TeamTuesday/siso-backend, pull requests merged in 2023-02, with the labels that each got.

#30 [SISO-104] 대표의견 조회 API
  libs/config/ormconfig.ts
  libs/config/src/database/database.service.ts
  src/app.module.ts
  src/comments/comments.controller.spec.ts
  src/comments/comments.controller.ts
  src/comments/comments.module.ts
  src/comments/comments.service.spec.ts
  src/comments/comments.service.ts
  src/comments/entities/comments.entity.ts
Labels: size/L

#32 Feat: [SISO-130] 투표하기 API Request Body에 validation 추가
  .gitignore
  package.json
  src/main.ts
  src/vote-subjects/vote-subjects.service.ts
  src/vote-vote/dtos/create-vote.dto.ts
  src/vote-vote/enums/vote-type.ts
  src/vote-vote/vote-vote.controller.ts
  src/vote-vote/vote-vote.service.ts
  yarn.lock
Labels: size/M

#31 [SISO-132] comment migration 파일 생성
  package.json
  src/migration/1676169142386-Comment.ts
Labels: size/S

#33 feat: 베스트 댓글에 대한 swagger response작성
  src/comments/comments.controller.ts
  src/comments/dto/comments.dto.ts
Labels: size/M

#34 feat: 투표 주제에 대한 swagger response작성
  src/vote-subjects/dto/vote-subjects.dto.ts
  src/vote-subjects/vote-subjects.controller.ts
Labels: size/M
